// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4MqKQXfLXkdWUZTOQQcKgvqPXgp6KPI',
    appId: '1:596114579222:web:afaa15cb3e5589a8a97a37',
    messagingSenderId: '596114579222',
    projectId: 'cloudapplication-cebe5',
    authDomain: 'cloudapplication-cebe5.firebaseapp.com',
    storageBucket: 'cloudapplication-cebe5.firebasestorage.app',
    measurementId: 'G-DDD9V12C8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLWKBFuPeSPV3zaEl_zYisJId_KmYJWg',
    appId: '1:596114579222:android:ac46db5e55830fafa97a37',
    messagingSenderId: '596114579222',
    projectId: 'cloudapplication-cebe5',
    storageBucket: 'cloudapplication-cebe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFTH8WlPfCc2qvY0cBfWSO6ciXTmqiL7A',
    appId: '1:596114579222:ios:658694c3d8f652c1a97a37',
    messagingSenderId: '596114579222',
    projectId: 'cloudapplication-cebe5',
    storageBucket: 'cloudapplication-cebe5.firebasestorage.app',
    iosBundleId: 'com.example.cloudTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFTH8WlPfCc2qvY0cBfWSO6ciXTmqiL7A',
    appId: '1:596114579222:ios:658694c3d8f652c1a97a37',
    messagingSenderId: '596114579222',
    projectId: 'cloudapplication-cebe5',
    storageBucket: 'cloudapplication-cebe5.firebasestorage.app',
    iosBundleId: 'com.example.cloudTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP4MqKQXfLXkdWUZTOQQcKgvqPXgp6KPI',
    appId: '1:596114579222:web:64b987f8762b1014a97a37',
    messagingSenderId: '596114579222',
    projectId: 'cloudapplication-cebe5',
    authDomain: 'cloudapplication-cebe5.firebaseapp.com',
    storageBucket: 'cloudapplication-cebe5.firebasestorage.app',
    measurementId: 'G-WDKT09DZ7F',
  );
}
