name: CI/CD Pipeline with Firebase App Distribution

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Verify Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub add mockito

      - name: Run tests
        run: |
          flutter test --coverage
        env:
          FLUTTER_TEST: true

      - name: Set up Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_SECRET }}" > ${HOME}/firebase-key.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}

      - name: Build Android APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution (Android)
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:255092478696:android:3b1d36cacb09f4da676f5d --groups ziadTesting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}