name: Firebase App Distribution

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build your app here, e.g., using Gradle or Android Studio

      - name: Upload App Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk

      - name: Deploy to Firebase App Distribution
        uses: google-github-actions/deploy-firebase-app-distribution@v0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          groups: tester
          releaseNotes: This is a new release
          file: app/build/outputs/apk/release/app-release.apk